---
title: "Kiglics BAN502 RRefresher Assignment"
author: "Allison Kiglics"
date: "5/14/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r include = FALSE}
#install.packages("tidyverse")
library("tidyverse")
```

```{r Task2}
diamonddata = diamonds

str(diamonddata)
summary(diamonddata)

### The dataset "diamonddata" contains 53940 observations of 10 variables
```
```{r Task3}
ggplot(diamonddata, aes(x= carat, y= price)) +
  geom_point()

### As shown by the plot, there is a positive correlation between carat and price, with price increasing with carat size.
```


```{r Task4}
ggplot(diamonddata, aes(x= carat, y= price, color = cut)) +
  geom_point()

### When color is added by cut, we can see that the premium and ideal cuts have a higher price per carat than the fair and good cuts
```

```{r Task5}
ggplot(diamonddata, aes(x= carat, y= price, color = cut)) +
  geom_point() +
  facet_wrap(~color)

### The faceted plots show diamonds with D, E, F and G colors increase in price per carat at a faster rate than diamonds with colors of H, I and J. Additionally, diamonds with a cut of fair are more often in colors H and J.
```

```{r Task6}
InventoryData <- read_csv("InventoryData.csv")
#View(InventoryData)

str(InventoryData)
summary(InventoryData)

### The data frame InventoryData has 13561 observations of 6 variables
```

```{r Task7}
inventoryA <- InventoryData %>%
  filter(Supplier == "A")

### There are 3695 observations in data frame inventoryA
```

```{r Task8}
inventoryA = mutate(inventoryA, OnHandRatio = `On Hand` / `Annual Demand`)

### The code above added a new column to the data frame called OnHandRatio, which was a calculated value of the variables On Hand divided by Annual Demand
```

```{r Task 9}
avg_cost <- InventoryData %>%
  group_by(`Item SKU`) %>%
  summarize(SKUAveCost = mean(`Cost per Unit ($)`))
```

```{r Task 10}
### In my former course that utilized R, I had a difficult time remembering the language and various commands (such as filter, select, arrange, mutate, etc). Thankfully for this course I've been able to dust them off and I'm remembering more easily. I also frequently got frustrated when I couldn't determine the errors in my code, only for it to be something like a missing quotation mark or a misplaced capitalization. I suppose that error catching will come easier as I become more comfortable in R. I also struggled with formatting plots. Things like changing the wrap, text size, text location and other plot related details were difficult for me to grasp.
```

